version: '3'

services:
  database:
    image: mysql:5.7
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    env_file: ./order_service/order_service/.env
    volumes:
      - .docker-cache/mysql_import:/docker-entrypoint-initdb.d
      - .docker-cache/mysql.conf.d:/etc/mysql/mysql.conf.d
      - .docker-cache/mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  order-service:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ./order_service/order_service/.env
    volumes:
      - ./order_service:/code
    ports:
      - "8000:8000"
    depends_on:
      - database

  product-service:
    image: rodolpheche/wiremock:2.23.2-alpine
    command: --verbose
    volumes:
      - ./wiremock/product-service/stubs:/home/wiremock
    ports:
    - "8081:8080"

  user-service:
    image: rodolpheche/wiremock:2.23.2-alpine
    command: --verbose
    volumes:
      - ./wiremock/user-service/stubs:/home/wiremock
    ports:
    - "8082:8080"

  rabbitmq:
    image: rabbitmq:3.7.15-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=hellofresh
      - RABBITMQ_DEFAULT_PASS=food
    ports:
      - "5672:5672"
      - "15672:15672"
  redis:
    image: "redis:alpine"

  celery:
    build: .
    command: celery -A order_service worker -l info
    volumes:
      - ./order_service:/code
    env_file: ./order_service/order_service/.env
    depends_on:
      - database
      - redis
      - order-service
